### ISSUE TITLE
File paths

### ISSUE THREAD

**Issue by MartinKolarik** [jsdelivr/api#117]
Currently, file paths are relative to the project version. E.g:

```
http://api.jsdelivr.com/v1/jsdelivr/libraries/jquery/2.2.0

[
  "jquery.js",
  "jquery.min.js",
  "jquery.min.map"
]
```

To construct an absolute URL on the CDN, we can join the project name, version, and file name. This, however, does't work for jquery CDN, as they use different file structure, so for jquery CDN, we currently we return paths relative to the CDN root instead.

We discussed this with @jimaek and agreed it's probably OK to leave it as-is and document the difference. However, after #56, we now have similar problem with the bootswatch theme projects. File paths there are relative to the boostwatch directory, so it isn't possible to construct a CDN URL without some custom logic and if we changed them to be relative to the CDN root, it'd be inconsistent with other project on bootstrap CDN.

**Comment by jimaek** [comment]
What do you suggest in this case?

**Comment by MartinKolarik** [comment]
@jimaek Not sure.

@markcarver thoughts?

**Comment by markcarver** [comment]
First, this issue should be tagged with `v2`. Thanks for cleaning up/solidifying the API versions btw!

---

I kind of touched on this issue and had similar concerns as I have previously mentioned in (starting at) https://github.com/jsdelivr/api/issues/56#issuecomment-108676345.

I think the specific version endpoint should really spit out the object that is already nested in the level above (e.g. http://api.jsdelivr.com/v1/jsdelivr/libraries/jquery). Then a  `baseUrl` property (or something like that) could be added to each asset/version that points to the working path relatively to what is actually _in_ the `files` array, e.g.:

http://api.jsdelivr.com/v1/jsdelivr/libraries/jquery:
```js
[
  {
    name: "jquery",
    // ... other meta
    assets: [
      // ... previous versions
      {
        baseUrl: "https://cdn.jsdelivr.net/jquery/2.2.0/", // <----- New URL property
        files: [
          "jquery.js",
          "jquery.min.js",
          "jquery.min.map"
        ],
        version: "2.2.0",
        mainfile: "jquery.min.js"
      },
      // ... newer versions
    ]
  }
]
```

http://api.jsdelivr.com/v1/jsdelivr/libraries/jquery/2.2.0:
```js
{
  baseUrl: "https://cdn.jsdelivr.net/jquery/2.2.0/", // <----- New URL property
  files: [
    "jquery.js",
    "jquery.min.js",
    "jquery.min.map"
  ],
  version: "2.2.0",
  mainfile: "jquery.min.js"
}
```

**Comment by MartinKolarik** [comment]
Sounds good, and it would work for the jquery cdn as well, although I'd probably change it to:
```js
{
  basePath: "/jquery/2.2.0/", // <----- New URL property
  files: [
    "jquery.js",
    "jquery.min.js",
    "jquery.min.map"
  ],
  version: "2.2.0",
  mainfile: "jquery.min.js"
}
```

@jimaek what do you think?

**Comment by markcarver** [comment]
Is there actually a technical reason why it can't be the entire URL? I cannot imagine this being the case since it would seem like a simple variable injection on your part.

`basePath` does not really solve the entire problem. This still means that consumers will have to do extra work (like I'm currently doing) to concatenate the fully qualified URL.

To give you an example of why this is important (from my point of view): https://www.drupal.org/node/2366307
https://www.drupal.org/node/2452617

Basically, BootstrapCDN changed their domain from `netdna.bootstrapcdn.com` to `maxcdn.bootstrapcdn.com`. This was one the primary reasons I switched to jsDelivr (among others).

As it stands now, I'm manually constructing this hypothetical `baseUrl` in my code, but it's still technically hard-coded. What happens if, for whatever reason, jsDelivr has to change it's CDN domain name in the future? That means all existing and currently hard-coded apps would break (again).

By adding the full `baseUrl`, you would allow consumers of the API to use this new property instead of having to construct it themselves.

**Comment by jimaek** [comment]
Well if we add a basepath parameter we might as well add the actual domain to it. I guess it would have to be configured in config.js since its rarely changed and its not possible to autodetect.
Any idas @MartinKolarik ?

**Comment by MartinKolarik** [comment]
There is no technical reason not to include the domain, I just didn't see the point. If it really changed, i'd break all the sites relying on the CDN. I just checked and `netdna.bootstrapcdn.com` still works.

@jimaek yes, config.js would be the right place.

**Comment by markcarver** [comment]
> I just didn't see the point

Sure. There's always a debate determining whether a URL should be absolute or relative. From my experience with APIs (especially [popular ones](https://developer.github.com/v3/repos/contents/#response-if-content-is-a-directory)), I would say that absolute URLs tend to offer more "stability" for end user consumption. This allows the user to simply consume what it's given instead of having to worry about performing addition logic after consumption.

That being said, I don't think changing the `files` array to absolute URLs is the way to go either. There is, indeed, actual usefulness in keeping them relative to the library for consumption/iteration purposes.

I would say that to offset that decision though , a separate `baseUrl` would be needed to compensate for that and `basePath` would be insufficient for those consumption needs.

> I just checked and netdna.bootstrapcdn.com still works.

They must have added it back at some point, but it _was_ broke for a long time.

**Comment by jimaek** [comment]
So we need to add 2 parameters?
```
basePath: "/jquery/2.2.0/",
domain: "cdn.jsdelivr.net"
```

Will this fix all of our current issues?

**Comment by markcarver** [comment]
No, not unless anyone really thinks that's truly needed.

A single fully qualified URL parameter should be all that's needed:
```
baseUrl: "https://cdn.jsdelivr.net/jquery/2.2.0/"
```

**Comment by MartinKolarik** [comment]
Ok, let's go with `baseUrl`. That should be enough.

**Comment by jimaek** [comment]
:+1:

**Comment by jimaek** [comment]
@markcarver What do you think? https://jsdelivr-api.herokuapp.com/v2/jsdelivr/library/jquery

**Comment by markcarver** [comment]
:smiley: This makes me _very_ happy!!!
