### ISSUE TITLE
Add analytics

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/api#62]
I am now parsing our access logs and populating a mysql DB with the number of hits per project.

What is the best way to make this data public? Should we create a new endpoint e.g. `api.jsdelivr.com/v2/analytics/` or just a new field inside each project with the reporting data?

I guess api-sync can pull the data itself from the DB(and cache it), right? No need for me to write a proxy between the DB and the API, correct?
The data we have is: date, project, hits. 

@megawac @UnbounDev

**Comment by megawac** [comment]
Do you keep any records of the version being downloaded

**Comment by jimaek** [comment]
No, just the number of hits for each project, all files and all versions in a single day.

**Comment by UnbounDev** [comment]
The data for analytics is rarely in sync w/ the actual library API data (since #60 specifies a 4 min sync cycle), for that reason alone I'd prefer to keep this on a separate endpoint (e.g. /v2/jsdelivr/**analytics**/fontawesome or /v2/jsdelivr/**metrics**/fontawesome) - but the separate endpoint also allows us to expand the data exposed by analytics w/o worrying about increasing standard API payloads.

Also - it's good to populate the database using access logs as a seed, would you want to implement a thin metrics reporting layer in the API? I could easily send a call to update counters in mysql land after executing an API request, this has the added benefit of allowing us to add metric counters for any traffic that flows through the API.

**Comment by jimaek** [comment]
To be clear, the pingdom data (4 min sync) and this are completely separate.
I control the DB and its contents so you can hit as often as you can as long as we follow the best perf practices. The data on analytics is also not real-time. (for pingdom its crucial to have real time data to pick up downtime)
KeyCDN has a delay of 10 minutes. CloudFlare 30 minutes. MaxCDN 3 hours.

A separate endpoint sounds good. I am not sure I understand the second part of your message. Either I am missing something or you miss-understood how the reporting works.

**Comment by jimaek** [comment]
I am thinking something like this:
```
GET api.jsdelivr.com/v2/analytics/bootstrap (default 30 days)

{
"2015-06-01": 17236457,
"2015-06-02": 15636655,
"2015-06-03": 17636236,
...

}

GET api.jsdelivr.com/v2/analytics/bootstrap?date_from=2015-05-01&date_to=2015-05-20

{
"2015-05-01": 17236457,
"2015-05-02": 15636655,
"2015-05-03": 17636236,
...
}

```

Do you think we can make `api.jsdelivr.com/v2/analytics/` show data for all the projects we host or its too much data to show?
Any feedback?

**Comment by UnbounDev** [comment]
If we really only intend to serve 'hit count per day' metrics this works find, but this does leave us w/o the ability to add metric types at that endpoint. I am a little concerned about the amount of data load this could cause the API to hold in memory (all libraries metrics, for what period of time?), perhaps this endpoint should query your mysql db?

@jimaek the point I was making before (about a thin 'metrics' layer): rather than have you parse the logs and input data to mysql, why not have the updates happen in real time? API could easily return a response to the endpoint user and then update SQL counters in your db (after the call completes).

**Comment by jimaek** [comment]
@UnbounDev I still dont get it. 
>API could easily return a response to the endpoint user

You mean `api.jsdelivr.com/v2/analytics/`?

>and then update SQL counters in your db 

Why would you do that?

I agree that you can specify the TTL for in-memory caching to be very low and query the DB much more often.

**Comment by UnbounDev** [comment]
Oh I see the confusion; an example of what I'm suggesting is this:

1. Call is made to, say, `api.jsdelivr.com/v2/jsdelivr/library/bootstrap`.
2. Response from query is sent to the endpoint user.
3. After the call, an 'update analytics' call is made to SQL; either creating the row `bootstrap ; <date>; <counter>` or updating the corresponding rows `<counter>` column.

I'm suggesting this as an alternative to posthumously parsing the access logs to acquire the same data.

**Comment by jimaek** [comment]
I think you are confused about what the analytics are. They are not API analytics, but CDN analytics.
MaxCDN/CloudFlare/KeyCDN logs are all parsed and then made available in the DB.
All you have to do is pull the data from there.

So if someone opens `//cdn.jsdelivr.net/jquery/2.1.4/jquery.min.js` in his browser then thats +1 hit for jquery.

**Comment by UnbounDev** [comment]
You're entirely correct - I thought we were parsing our own access logs, thanks that clears up my confusion.

**Comment by jimaek** [comment]
Great :) So back to the point. I purpose this https://github.com/jsdelivr/api/issues/62#issuecomment-110081984

**Comment by jimaek** [comment]
Ping @megawac and @UnbounDev 
The analytics DB is accessible, ping me to give you the access info.

**Comment by jimaek** [comment]
@UnbounDev 
https://jsdelivr-api.herokuapp.com/v2/analytics/bootstrap
```
{

    "status": 500,
    "message": "Pool is destroyed",
    "url": "/bootstrap"

}
```

**Comment by jimaek** [comment]
Sorry my mistake. Looks good so far! Thanks
